import type { Metadata } from "next";
import { Inter, Ultra } from "next/font/google";
import "./globals.css";

// const ultra = Ultra({
//   subsets: ['latin'],
//   variable : '--font-sans'

// })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">{children}</body>
    </html>
  );
}
